### ISSUE TITLE
VMD to bvh

### ISSUE THREAD

**Issue by HHIR** [Dene33/dae_fbx_to_bvh#1]
Dear @Dene33 
I want to ask you, do you have any suggestion for VMD(MMD) to BVH ?

**Comment by Dene33** [comment]
> Dear @Dene33
> I want to ask you, do you have any suggestion for VMD(MMD) to BVH ?

Have you tried [this?](https://github.com/sugiany/blender_mmd_tools) As I can see, you can easily import the models and animations. After that just File > Export > .bvh

Or do you need batch exporter?

**Comment by HHIR** [comment]
@Dene33 This one is just for importing models from MikuMikuDance to blender.
 but I just want to use VMD motion data to my own model on Blender.
 for example, I have one model on blender right now, (this one: https://free3d.com/3d-model/female-robot-39128.html)
and there is some motion dancing on MikuMikuDance which is VMD format and I want to use VMD on mention model in the blender and rendering together.
is there any idea?

**Comment by HHIR** [comment]
![image](https://user-images.githubusercontent.com/20298402/49406224-3f3c5700-f755-11e8-92ae-51bb4598acc4.png)
as you can see exporting BVH is unavailable!
but my model has motion with VMD, and it seems blender doesn't have the ability to converting VMD to BVH!!!!!!
But I'm sure, should be some way...

**Comment by Dene33** [comment]
> ![image](https://user-images.githubusercontent.com/20298402/49406224-3f3c5700-f755-11e8-92ae-51bb4598acc4.png)
> as you can see exporting BVH is unavailable!
> but my model has motion with VMD, and it seems blender doesn't have the ability to converting VMD to BVH!!!!!!
> But I'm sure, should be some way...

I suppose, you should select armature object before the export.

**Comment by HHIR** [comment]
wow, that's working. :)
accept my apologies for simple questions, cause I'm a beginner in Blender. can you please give me information about importing this BVH to one model?
I saw some video on youtube but my blender version is 2.8 and is a little different with old ones.

**Comment by Dene33** [comment]
Try [this](http://www.makehumancommunity.org/wiki/Documentation:MakeWalk#Retargeting). Works great with rigify, not sure what rig do you have but give it a try.
